#!/usr/bin/env bash
# Builds scripts/db/consolidated-pending.sql — the paste-ready script for the
# Supabase SQL Editor containing exactly the migrations that have never been
# applied to production, in version order.
#
# Usage:
#   scripts/db/build-consolidated.sh           regenerate the artifact
#   scripts/db/build-consolidated.sh --list    print the pending file list
#
# Single source of truth for "what is still pending" lives in the `pending`
# array below. When a migration has been applied to production, remove it
# from the array and regenerate.
set -euo pipefail

cd "$(dirname "$0")/../.."

# 2026-08-26: profiles context fields (feat/profile-dashboard) await the SQL
# Editor paste. Once applied, empty this array again and regenerate.
pending=(
  supabase/migrations/20260826000000_profiles_context_fields.sql
)

if [ "${1:-}" = "--list" ]; then
  printf '%s\n' ${pending[@]+"${pending[@]}"}
  exit 0
fi

for f in ${pending[@]+"${pending[@]}"}; do
  if [ ! -f "$f" ]; then
    echo "error: listed pending migration not found: $f" >&2
    exit 1
  fi
done

out="scripts/db/consolidated-pending.sql"

{
  echo "-- ============================================================================"
  echo "-- BSIT Survival Kit — consolidated PENDING migrations (paste-ready)"
  echo "-- ============================================================================"
  echo "-- Purpose : one script to paste into the Supabase SQL Editor that applies"
  echo "--           every migration never yet run against production. Applying it is"
  echo "--           equivalent to running the ${#pending[@]} source files below in order."
  echo "--"
  echo "-- Generated by scripts/db/build-consolidated.sh (do not edit by hand;"
  echo "-- edit the source files and re-run the script)."
  echo "--"
  echo "-- Source files, applied in this order:"
  i=1
  for f in ${pending[@]+"${pending[@]}"}; do
    echo "--   $i. $f"
    i=$((i + 1))
  done
  cat <<'HEADER'
--
-- IDEMPOTENCY CONTRACT: the SQL Editor can be re-pasted after a partial or
-- failed attempt, so EVERY statement below must be safe to re-run. Tables and
-- indexes are created IF NOT EXISTS, functions use CREATE OR REPLACE,
-- policies are preceded by DROP POLICY IF EXISTS, and grants/revokes are
-- naturally repeatable. Keep new statements inside this contract.
-- ============================================================================

HEADER

  for f in ${pending[@]+"${pending[@]}"}; do
    printf -- '\n-- ----------------------------------------------------------------\n'
    printf -- '-- Source: %s\n' "$f"
    printf -- '-- ----------------------------------------------------------------\n\n'
    cat "$f"
    printf '\n'
  done
} > "$out"

echo "wrote $out (${#pending[@]} pending migrations)"
