-- ============================================================================
-- BSIT Survival Kit — consolidated PENDING migrations (paste-ready)
-- ============================================================================
-- Purpose : one script to paste into the Supabase SQL Editor that applies
--           every migration never yet run against production. Applying it is
--           equivalent to running the 5 source files below in order.
--
-- Generated by scripts/db/build-consolidated.sh (do not edit by hand;
-- edit the source files and re-run the script).
--
-- Source files, applied in this order:
--   1. supabase/migrations/20260808000000_growth_identity_agg.sql
--   2. supabase/migrations/20260808000001_growth_funnel_agg.sql
--   3. supabase/migrations/20260808000002_growth_audience_agg.sql
--   4. supabase/migrations/20260808000003_growth_retention_agg.sql
--   5. supabase/migrations/20260821000001_dash_exit_agg.sql
--
-- IDEMPOTENCY CONTRACT: the SQL Editor can be re-pasted after a partial or
-- failed attempt, so EVERY statement below must be safe to re-run. Tables and
-- indexes are created IF NOT EXISTS, functions use CREATE OR REPLACE,
-- policies are preceded by DROP POLICY IF EXISTS, and grants/revokes are
-- naturally repeatable. Keep new statements inside this contract.
-- ============================================================================


-- ----------------------------------------------------------------
-- Source: supabase/migrations/20260808000000_growth_identity_agg.sql
-- ----------------------------------------------------------------

-- growth_identity_agg: every population that anyone might call a "user",
-- counted once, in one place, under names that cannot be confused.
--
-- Why this exists. docs/POST-MORTEM.md records a "total signed-up users"
-- figure about an order of magnitude larger than the number of rows in
-- auth.users. The most likely cause is that the earlier figure counted DEVICES
-- under the device-first identity model that predates accounts: lib/device.ts
-- mints a UUID into localStorage on first visit and every analytics event is
-- keyed on it. Rather than decide which figure was "right", this function
-- returns both under unambiguous names so no report can conflate them again.
--
-- Every count is computed in Postgres. None of these can be done from the
-- client: PostgREST caps a select at 1000 rows and `events` is far past that,
-- so a client-side count(distinct) would silently truncate.
create or replace function growth_identity_agg()
returns json
language sql
security definer
set search_path = public
as $$
  select json_build_object(
    -- ACCOUNTS. A row in auth.users. Never call this "users" in a report.
    'accounts',              (select count(*) from auth.users),
    'accounts_confirmed',    (select count(*) from auth.users
                                where email_confirmed_at is not null),
    'profiles',              (select count(*) from profiles),

    -- REACH. A device is one browser that stored a device_id in localStorage.
    -- devices_entered is the canonical Growth reach number.
    'devices_entered',       (select count(distinct device_id) from events
                                where event_type = 'enter'),
    -- Will exceed devices_entered: a device arriving on a shared module link
    -- emits module_open without ever emitting enter. The gap is the deep-link
    -- population, and it is why the funnel is not guaranteed monotonic.
    'devices_any_event',     (select count(distinct device_id) from events),

    -- MONEY. Distinct devices in the ledger and in the entitlement table.
    'devices_paid',          (select count(distinct device_id) from payments),
    'devices_subscribed',    (select count(distinct device_id) from subscriptions),
    'subscriptions_active',  (select count(*) from subscriptions
                                where status = 'active'
                                  and current_period_end > now()),

    -- THE BRIDGE between the two identity models. A low ratio here means the
    -- device-first population never became accounts, which is the fact that
    -- makes the two headline numbers differ.
    'payments_with_user_id', (select count(*) from payments where user_id is not null),
    'payments_total',        (select count(*) from payments),

    -- OTHER POPULATIONS that get loosely called "users" in conversation.
    'waitlist_emails',       (select count(distinct lower(email)) from waitlist),
    'class_member_devices',  (select count(distinct device_id) from class_members),
    'feedback_devices',      (select count(distinct device_id) from user_feedback)
  );
$$;

revoke execute on function growth_identity_agg() from public, anon, authenticated;
grant execute on function growth_identity_agg() to service_role;


-- ----------------------------------------------------------------
-- Source: supabase/migrations/20260808000001_growth_funnel_agg.sql
-- ----------------------------------------------------------------

-- growth_funnel_agg: distinct-device counts for each step of the LIVE funnel
-- inside a window, plus completion from the payments ledger.
--
-- The live path is:
--   enter -> year_select -> subject_open -> module_open
--         -> paywall_teaser_view -> paywall_teaser_click -> subscribe_click
--         -> paid (ledger)
--
-- There is NO completion event. `unlock_submitted` was the "they paid" step
-- before the subscription pivot and nothing replaced it. The ledger is the
-- better source anyway: a payments row is written by a signature-verified
-- webhook, while a client beacon is lost whenever a user bounces to GCash and
-- never returns.
--
-- Windows are half-open [p_since, p_until) so consecutive weeks abut exactly
-- and no event is counted in two of them.
create or replace function growth_funnel_agg(
  p_since timestamptz,
  p_until timestamptz
)
returns json
language sql
security definer
set search_path = public
as $$
  with windowed as (
    select device_id, event_type, subject_id
    from events
    where created_at >= p_since
      and created_at <  p_until
  ),
  steps as (
    select
      count(distinct device_id) filter (where event_type = 'enter')                as enter,
      count(distinct device_id) filter (where event_type = 'year_select')          as year_select,
      -- subject_open fires on TWO pages. The subject LIST page emits it with
      -- year_id only (app/(main)/year/[yearId]/subjects/page.tsx); the modules
      -- page emits it WITH subject_id, which is the real "opened a subject".
      -- The funnel step means the latter.
      count(distinct device_id) filter (where event_type = 'subject_open'
                                          and subject_id is not null)              as subject_open,
      -- Unfiltered, so the inflation caused by the list page stays visible.
      count(distinct device_id) filter (where event_type = 'subject_open')         as subject_open_any,
      count(distinct device_id) filter (where event_type = 'module_open')          as module_open,
      count(distinct device_id) filter (where event_type = 'paywall_teaser_view')  as paywall_teaser_view,
      count(distinct device_id) filter (where event_type = 'paywall_teaser_click') as paywall_teaser_click,
      count(distinct device_id) filter (where event_type = 'subscribe_click')      as subscribe_click,
      -- Every device that did anything. Exceeds `enter` by the deep-link
      -- population, which is why the funnel is not guaranteed monotonic.
      count(distinct device_id)                                                    as any_event
    from windowed
  ),
  checkout_devices as (
    select distinct device_id
    from windowed
    where event_type = 'subscribe_click'
  ),
  ledger as (
    select
      count(distinct p.device_id)                                        as paid,
      count(distinct p.device_id) filter (where c.device_id is not null)  as paid_after_subscribe_click
    from payments p
    left join checkout_devices c on c.device_id = p.device_id
    where p.paid_at >= p_since
      and p.paid_at <  p_until
  ),
  entitlements as (
    -- Handed across to Finance: a subscription created in the window without a
    -- matching payment is either comped access or a webhook granting
    -- entitlement without recording money.
    select count(distinct device_id) as subscriptions_created
    from subscriptions
    where created_at >= p_since
      and created_at <  p_until
  ),
  dead as (
    -- DELIBERATELY NOT WINDOWED. The claim is "no code has emitted these since
    -- the pivot", and only an all-time count plus a last-seen timestamp can
    -- evidence that. A windowed zero proves nothing.
    select
      count(*) filter (where event_type = 'unlock_click')     as unlock_click_rows,
      count(*) filter (where event_type = 'unlock_submitted') as unlock_submitted_rows,
      max(created_at) filter (
        where event_type in ('unlock_click', 'unlock_submitted')
      ) as dead_last_seen
    from events
  )
  select json_build_object(
    'since',        p_since,
    'until',        p_until,
    'steps',        (select row_to_json(s) from steps s),
    'ledger',       (select row_to_json(l) from ledger l),
    'entitlements', (select row_to_json(e) from entitlements e),
    'dead_events',  (select row_to_json(d) from dead d)
  );
$$;

revoke execute on function growth_funnel_agg(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function growth_funnel_agg(timestamptz, timestamptz) to service_role;


-- ----------------------------------------------------------------
-- Source: supabase/migrations/20260808000002_growth_audience_agg.sql
-- ----------------------------------------------------------------

-- growth_acquisition_agg: where visitors came from, in a window.
--
-- Attribution is captured on `enter` events only — see getAttribution() in
-- lib/analytics.ts, which runs for that event type and no other. Values are
-- sanitized and length-capped by app/api/events/route.ts before insert.
--
-- Referrers are stored as full URLs, so they are reduced to a host here.
-- Fifty distinct deep links from one platform are one source, not fifty.

-- This migration is the SOLE creator of events_type_created_idx. No other
-- migration creates it — confirmed by grepping
-- 20260808000003_growth_retention_agg.sql, which consumes it but does not
-- create it (see below).
--
-- It has two consumers. This file's `enters` CTE just below filters
-- `events` on `event_type = 'enter'` AND a `created_at` range in the same
-- WHERE clause, before any aggregation happens — a composite
-- (event_type, created_at desc) index narrows that scan directly.
-- `growth_content_agg`'s `opens` CTE in
-- 20260808000003_growth_retention_agg.sql filters the identical shape
-- (`event_type = 'module_open'` AND a `created_at` range against the base
-- table) and relies on this same index existing, without creating it
-- itself. `growth_funnel_agg`'s `windowed` CTE looked like a candidate
-- consumer too, but its event_type predicates live only inside aggregate
-- FILTER clauses, which restrict which already-scanned rows get counted,
-- not which rows the scan reads — that mismatch is why the index was
-- removed from that migration (commit af9ffc7) and landed here instead.
-- `if not exists` is kept for safety if this migration is ever re-applied,
-- not because a second migration also creates this index — none does.
create index if not exists events_type_created_idx
  on events (event_type, created_at desc);

create or replace function growth_acquisition_agg(
  p_since timestamptz,
  p_until timestamptz
)
returns json
language sql
security definer
set search_path = public
as $$
  with enters as (
    select device_id, referrer, utm_source, utm_medium, utm_campaign
    from events
    where event_type = 'enter'
      and created_at >= p_since
      and created_at <  p_until
  )
  select json_build_object(
    'enters',  (select count(*) from enters),
    'devices', (select count(distinct device_id) from enters),
    -- The dark-social signal: links arriving through group chats rather than
    -- search or a linked profile.
    'no_referrer', (select count(*) from enters
                      where referrer is null or referrer = ''),
    -- Capped distributions below are wrapped as { rows, total_groups } so a
    -- reader can tell "top 15 of 15" (complete) from "top 15 of 40"
    -- (truncated) rather than the bare array implying completeness either
    -- way. total_groups is the number of groups the GROUP BY would have
    -- produced with no LIMIT applied.
    'by_referrer_host', (
      with hosts as (
        select
          coalesce(
            nullif(split_part(split_part(referrer, '://', 2), '/', 1), ''),
            '(none)'
          ) as host,
          count(*)::int as count
        from enters
        group by 1
      )
      select json_build_object(
        'rows', (
          select json_agg(row_to_json(t))
          from (select host, count from hosts order by count desc limit 15) t
        ),
        'total_groups', (select count(*)::int from hosts)
      )
    ),
    'by_utm_source', (
      with sources as (
        select
          coalesce(utm_source, '(none)') as utm_source,
          coalesce(utm_medium, '(none)') as utm_medium,
          count(*)::int as count
        from enters
        group by 1, 2
      )
      select json_build_object(
        'rows', (
          select json_agg(row_to_json(t))
          from (select utm_source, utm_medium, count from sources order by count desc limit 15) t
        ),
        'total_groups', (select count(*)::int from sources)
      )
    ),
    'by_utm_campaign', (
      with campaigns as (
        select utm_campaign, count(*)::int as count
        from enters
        where utm_campaign is not null
        group by utm_campaign
      )
      select json_build_object(
        'rows', (
          select json_agg(row_to_json(t))
          from (select utm_campaign, count from campaigns order by count desc limit 15) t
        ),
        'total_groups', (select count(*)::int from campaigns)
      )
    )
  );
$$;

revoke execute on function growth_acquisition_agg(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function growth_acquisition_agg(timestamptz, timestamptz) to service_role;

-- growth_segment_agg: engagement and conversion split by year and by subject.
--
-- A blended average across a first-year-dominated audience hides everything
-- interesting, which is the whole reason this function exists.
--
-- University and device type are deliberately absent. profiles.university is
-- per-ACCOUNT, and accounts are a far smaller population than devices, so it
-- cannot be crossed with a device-keyed funnel — admin_profiles_agg() already
-- reports that distribution. lib/deviceType.ts is called only by
-- app/api/waitlist/route.ts and its output lands only on waitlist.device_type;
-- `events` has no device-type column at all.
create or replace function growth_segment_agg(
  p_since timestamptz,
  p_until timestamptz
)
returns json
language sql
security definer
set search_path = public
as $$
  with windowed as (
    select device_id, event_type, year_id, subject_id
    from events
    where created_at >= p_since
      and created_at <  p_until
  ),
  paid_devices as (
    select distinct device_id, year_id, subject_id
    from payments
    where paid_at >= p_since
      and paid_at <  p_until
  )
  select json_build_object(
    'by_year', (
      select json_agg(row_to_json(t))
      from (
        select
          y.label as year_label,
          count(distinct w.device_id) filter (
            where w.event_type = 'module_open')::int          as module_open_devices,
          count(distinct w.device_id) filter (
            where w.event_type = 'paywall_teaser_view')::int  as paywall_devices,
          (select count(distinct pd.device_id)
             from paid_devices pd where pd.year_id = y.id)::int as paid_devices
        from years y
        left join windowed w on w.year_id = y.id
        group by y.id, y.label, y.sort_order
        order by y.sort_order
      ) t
    ),
    'by_subject', (
      with subject_rows as (
        select
          s.title as subject_title,
          y.label as year_label,
          count(distinct w.device_id) filter (
            where w.event_type = 'module_open')::int          as module_open_devices,
          count(distinct w.device_id) filter (
            where w.event_type = 'paywall_teaser_view')::int  as paywall_devices,
          -- NOT all paid devices for this subject — whole-year-plan payments
          -- have subject_id IS NULL (20260624120000_payments_ledger.sql:11)
          -- and can never match pd.subject_id = s.id, so this equality
          -- excludes them BY CONSTRUCTION. isSubscribed() (lib/subscriptions.ts)
          -- treats a null-subject year plan as unlocking every subject in
          -- that year, so those payers are real conversions, just not
          -- attributable to one subject out of the ~30 a year plan unlocks —
          -- attributing one payment across all of them would inflate every
          -- subject's count into a meaningless number. They are not missing:
          -- by_year.paid_devices (above) counts them correctly, because that
          -- join is on year_id, which a payment always has. Hence the name:
          -- this counts only devices whose paid plan was scoped to this one
          -- subject.
          (select count(distinct pd.device_id)
             from paid_devices pd where pd.subject_id = s.id)::int as subject_plan_paid_devices
        from subjects s
        join years y on y.id = s.year_id
        left join windowed w on w.subject_id = s.id
        group by s.id, s.title, y.label
        having count(w.device_id) > 0
      )
      select json_build_object(
        'rows', (
          select json_agg(row_to_json(t))
          from (
            select subject_title, year_label, module_open_devices, paywall_devices, subject_plan_paid_devices
            from subject_rows
            order by module_open_devices desc
            limit 25
          ) t
        ),
        'total_groups', (select count(*)::int from subject_rows)
      )
    )
  );
$$;

revoke execute on function growth_segment_agg(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function growth_segment_agg(timestamptz, timestamptz) to service_role;


-- ----------------------------------------------------------------
-- Source: supabase/migrations/20260808000003_growth_retention_agg.sql
-- ----------------------------------------------------------------

-- growth_cohort_agg: weekly device cohorts, return counts, and the trailing
-- weekly-active series.
--
-- Weeks are PH calendar weeks. `created_at at time zone 'Asia/Manila'`
-- converts the timestamptz to Manila wall-clock before truncation, so a week
-- boundary lands at Monday 00:00 in Manila rather than in UTC. Getting this
-- wrong shifts every bucket by eight hours and quietly moves activity between
-- weeks.
--
-- weekly_active exists because visits cluster around exam dates. Until the
-- term calendar in lib/reports/academicCalendar.ts is populated, this
-- trailing series is the only evidence-based way to tell a real engagement
-- drop from a normal quiet week. It reports exactly the p_weeks most
-- recently COMPLETED PH weeks — the current, still-in-progress week is
-- deliberately excluded (see the `weekly` CTE below): a partial week always
-- has fewer days of activity than a finished one purely because it isn't
-- over yet, so including it would read as a manufactured decline in the
-- newest bucket.
create or replace function growth_cohort_agg(p_weeks int default 8)
returns json
language sql
security definer
set search_path = public
as $$
  with first_seen as (
    select
      device_id,
      date_trunc('week', min(created_at) at time zone 'Asia/Manila')::date as cohort_week
    from events
    group by device_id
  ),
  activity as (
    -- Fetched over p_weeks + 2 weeks — wider than either consumer below
    -- strictly needs on its own — so `cohorts` always has activity data for
    -- its newest cohorts' return-rate buckets. `weekly` trims this down to
    -- exactly what it reports (see below); this CTE is left unnarrowed so
    -- `cohorts`'s correctness never depends on `weekly`'s needs.
    select distinct
      device_id,
      date_trunc('week', created_at at time zone 'Asia/Manila')::date as active_week
    from events
    where created_at >= now() - make_interval(weeks => p_weeks + 2)
  ),
  weekly as (
    -- Trimmed to the trailing p_weeks COMPLETE PH weeks: active_week must be
    -- on or after (this_week_start - p_weeks * 7 days) AND strictly before
    -- this_week_start. That upper bound is what excludes the current,
    -- still-in-progress week — without it, `activity`'s wider p_weeks + 2
    -- fetch above leaks 2 extra weeks plus a partial current week into this
    -- series, which is the bug this trim exists to fix. A week with zero
    -- active devices does not appear as a zero-count row (`group by` does
    -- not manufacture empty groups), so this returns AT MOST p_weeks rows,
    -- never more — see the migration's .test.md for the exact expected
    -- count and the query that verifies it.
    select active_week, count(*)::int as active_devices
    from activity
    where active_week >= date_trunc('week', (now() at time zone 'Asia/Manila'))::date - (p_weeks * 7)
      and active_week <  date_trunc('week', (now() at time zone 'Asia/Manila'))::date
    group by active_week
    order by active_week desc
  ),
  cohorts as (
    -- NO upper bound here, deliberately: the newest cohort's `size` is real
    -- and wanted, and trimming to complete weeks would throw it away.
    --
    -- The cost is that the current, still-in-progress week ALWAYS appears as a
    -- cohort whose returned_week_1 and returned_week_2 are STRUCTURALLY 0 --
    -- the weeks those columns measure have not happened yet. That zero is the
    -- calendar, not a retention collapse, and it will be zero every single run.
    -- Read the newest one or two cohort rows for `size` only. This is the same
    -- partial-period artifact `weekly_active` documents above, which solves it
    -- by trimming because it has no per-row value worth keeping.
    select
      f.cohort_week,
      count(distinct f.device_id)::int as size,
      -- Integer arithmetic on a date adds days in Postgres, so +7 is "the
      -- following week's bucket".
      count(distinct a.device_id) filter (
        where a.active_week = f.cohort_week + 7)::int  as returned_week_1,
      count(distinct a.device_id) filter (
        where a.active_week = f.cohort_week + 14)::int as returned_week_2
    from first_seen f
    left join activity a on a.device_id = f.device_id
    where f.cohort_week >=
      date_trunc('week', (now() at time zone 'Asia/Manila'))::date - (p_weeks * 7)
    group by f.cohort_week
    order by f.cohort_week desc
  )
  select json_build_object(
    'weekly_active', (select json_agg(row_to_json(w)) from weekly w),
    'cohorts',       (select json_agg(row_to_json(c)) from cohorts c)
  );
$$;

revoke execute on function growth_cohort_agg(int) from public, anon, authenticated;
grant execute on function growth_cohort_agg(int) to service_role;

-- growth_content_agg: which modules get opened versus finished.
--
-- High opens with low completion is a content problem wearing an engagement
-- costume, and it is the input to "what should I build next".
--
-- Returns { rows: [...], total_groups: N } rather than a bare array: `rows`
-- is capped at p_limit (ranked by open_devices desc), and total_groups is
-- the count of ALL modules with at least one module_open in the window,
-- before that cap — so a consumer can say "top N of M modules" instead of
-- presenting the capped list as the complete picture.
create or replace function growth_content_agg(
  p_since timestamptz,
  p_until timestamptz,
  p_limit int default 20
)
returns json
language sql
security definer
set search_path = public
as $$
  with opens as (
    select module_id, count(distinct device_id)::int as open_devices
    from events
    where event_type = 'module_open'
      and module_id is not null
      and created_at >= p_since
      and created_at <  p_until
    group by module_id
  ),
  completions as (
    select module_id, count(distinct device_id)::int as completed_devices
    from module_progress
    where completed_at >= p_since
      and completed_at <  p_until
    group by module_id
  )
  select json_build_object(
    'rows', (
      select json_agg(row_to_json(t))
      from (
        select
          m.title as module_title,
          s.title as subject_title,
          o.open_devices,
          coalesce(c.completed_devices, 0) as completed_devices
        from opens o
        join modules  m on m.id = o.module_id
        join subjects s on s.id = m.subject_id
        -- module_progress.module_id is TEXT while modules.id is UUID. Cast
        -- the UUID side to text: casting the text side to uuid would raise
        -- on the first non-uuid row ever written and take the whole report
        -- down for one bad record.
        left join completions c on c.module_id = m.id::text
        order by o.open_devices desc
        limit p_limit
      ) t
    ),
    'total_groups', (select count(*) from opens)
  );
$$;

revoke execute on function growth_content_agg(timestamptz, timestamptz, int)
  from public, anon, authenticated;
grant execute on function growth_content_agg(timestamptz, timestamptz, int) to service_role;

-- growth_demand_agg: what people ask for that does not exist yet.
--
-- The waitlist is the demand-sensing surface — ComingSoonModal and the paywall
-- both write into it (see the `source` check constraint). device_type is here
-- and nowhere else: lib/deviceType.ts is called only by
-- app/api/waitlist/route.ts, so this is the ONLY device-type segmentation the
-- product can produce.
--
-- `by_subject` is the one breakdown here capped by row count (top 20 by
-- signups) rather than drawn from a small, inherently bounded value set like
-- source, year, willing_to_pay, or device_type — so it alone is wrapped as
-- { rows: [...], total_groups: N } rather than a bare array, giving the
-- consumer the untruncated group count alongside the capped list.
create or replace function growth_demand_agg(
  p_since timestamptz,
  p_until timestamptz
)
returns json
language sql
security definer
set search_path = public
as $$
  with windowed as (
    select * from waitlist
    where created_at >= p_since and created_at < p_until
  )
  select json_build_object(
    'signups_window',   (select count(*) from windowed),
    'signups_all_time', (select count(*) from waitlist),
    'by_source', (
      select json_agg(row_to_json(t))
      from (select source, count(*)::int as count
              from windowed group by source order by count desc) t
    ),
    'by_year', (
      select json_agg(row_to_json(t))
      from (select coalesce(year_label, 'Unknown') as year_label, count(*)::int as count
              from windowed group by 1 order by count desc) t
    ),
    'by_subject', json_build_object(
      'rows', (
        select json_agg(row_to_json(t))
        from (select subject_title, coalesce(year_label, '') as year_label, count(*)::int as count
                from windowed where subject_title is not null
                group by subject_title, year_label order by count desc limit 20) t
      ),
      -- Total distinct (subject_title, year_label) groups in the window,
      -- before the top-20 cap above.
      'total_groups', (
        select count(*) from (
          select 1 from windowed where subject_title is not null
          group by subject_title, year_label
        ) g
      )
    ),
    'willing_to_pay', (
      select json_agg(row_to_json(t))
      from (select coalesce(willing_to_pay, 'unanswered') as answer, count(*)::int as count
              from windowed group by 1 order by count desc) t
    ),
    'by_device_type', (
      select json_agg(row_to_json(t))
      from (select device_type, count(*)::int as count
              from windowed group by device_type order by count desc) t
    )
  );
$$;

revoke execute on function growth_demand_agg(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function growth_demand_agg(timestamptz, timestamptz) to service_role;

-- growth_feedback_agg: the only department input written in users' own words.
--
-- Returns verbatim text on purpose — themes, not counts, are what this is for.
-- Safe only because docs/reports/ is gitignored in full and the repo is public.
-- Deliberately returns NO device_id, user_id, or coupon_code: the report needs
-- what was said, never who said it.
--
-- Note for future work: user_feedback.device_id is UUID while events.device_id
-- and payments.device_id are TEXT. Any join across them needs an explicit cast.
--
-- `recent` is wrapped as { rows: [...], total_groups: N } because it too is
-- capped, at p_limit, most-recent-first. total_groups counts every row in
-- the window with non-empty feedback_text, which is NOT the same number as
-- the sibling `rows_window` key: `rows_window` also counts rows with blank
-- feedback_text that `recent` excludes entirely, so `rows_window` cannot
-- substitute as `recent`'s own truncation signal.
create or replace function growth_feedback_agg(
  p_since timestamptz,
  p_until timestamptz,
  p_limit int default 40
)
returns json
language sql
security definer
set search_path = public
as $$
  with windowed as (
    select * from user_feedback
    where created_at >= p_since and created_at < p_until
  )
  select json_build_object(
    'rows_window',       (select count(*) from windowed),
    'rows_all_time',     (select count(*) from user_feedback),
    'avg_app_rating',    (select round(avg(app_rating), 2) from windowed),
    'avg_module_rating', (select round(avg(module_rating), 2) from windowed),
    'recent', json_build_object(
      'rows', (
        select json_agg(row_to_json(t))
        from (
          select
            w.created_at,
            w.app_rating,
            w.module_rating,
            w.feedback_text,
            m.title as module_title
          from windowed w
          left join modules m on m.id = w.module_id
          where coalesce(w.feedback_text, '') <> ''
          order by w.created_at desc
          limit p_limit
        ) t
      ),
      'total_groups', (
        select count(*) from windowed w where coalesce(w.feedback_text, '') <> ''
      )
    )
  );
$$;

revoke execute on function growth_feedback_agg(timestamptz, timestamptz, int)
  from public, anon, authenticated;
grant execute on function growth_feedback_agg(timestamptz, timestamptz, int) to service_role;


-- ----------------------------------------------------------------
-- Source: supabase/migrations/20260821000001_dash_exit_agg.sql
-- ----------------------------------------------------------------

-- dash_exit_agg: where students stop.
--
-- This is the dashboard's churn measure, and it is NOT subscription lapse. It
-- answers: how many devices open one module and never come back, how many
-- touch one subject and stop, and WHICH module or subject they were last seen
-- on. A drop-off number without an exit point tells you that you have a
-- problem; the exit point tells you where it is.
--
-- There is deliberately no identity function beside this one. The device and
-- account reconciliation the dashboard needs already exists as
-- growth_identity_agg() in 20260808000000_growth_identity_agg.sql, reviewed and
-- applied through the same checklist. A second implementation of "what counts
-- as a device" would be a second thing to keep in step, and the two would drift.
--
-- Windows are half-open: >= p_since, < p_until. Manila is the reporting
-- calendar everywhere else in this codebase, and the caller passes boundaries
-- already resolved in Manila terms.
create or replace function dash_exit_agg(
  p_since timestamptz,
  p_until timestamptz,
  p_limit int default 20
)
returns json
language sql
security definer
set search_path = public
as $$
  with activity as (
    -- module_open is the only event that names a module, so it is what "how
    -- far did they get" is built from. module_id is nullable on events (a
    -- deep link can arrive without one), and a null would join to nothing and
    -- silently shrink every count below, so it is excluded here rather than
    -- left to disappear in a join.
    select device_id, module_id, created_at
    from events
    where event_type = 'module_open'
      and module_id is not null
      and created_at >= p_since
      and created_at <  p_until
  ),
  -- Subject is taken from modules, never from events.subject_id: the same
  -- module always belongs to one subject, whereas the event column is
  -- populated inconsistently depending on the entry path.
  activity_scoped as (
    select a.device_id, a.module_id, m.subject_id, a.created_at
    from activity a
    join modules m on m.id = a.module_id
  ),
  per_device as (
    select
      device_id,
      count(distinct module_id)::int  as modules_opened,
      count(distinct subject_id)::int as subjects_touched,
      max(created_at)                 as last_seen
    from activity_scoped
    group by device_id
  ),
  depth as (
    select
      count(*)::int                                            as devices_total,
      count(*) filter (where modules_opened = 1)::int           as devices_one_module,
      count(*) filter (where modules_opened between 2 and 3)::int as devices_two_to_three_modules,
      count(*) filter (where modules_opened >= 4)::int          as devices_four_plus_modules,
      count(*) filter (where subjects_touched = 1)::int         as devices_one_subject,
      count(*) filter (where subjects_touched >= 2)::int        as devices_multi_subject
    from per_device
  ),
  -- The module each device was LAST seen on inside the window. distinct on
  -- with a matching order by is the Postgres idiom for "one row per group,
  -- picked by an ordering" and avoids a self-join against max(created_at),
  -- which would return two rows for a device that opened two modules in the
  -- same millisecond.
  last_module as (
    select distinct on (device_id)
      device_id, module_id, subject_id
    from activity_scoped
    order by device_id, created_at desc, module_id
  ),
  -- UNCAPPED group sets. total_groups below counts THESE, never the capped
  -- row lists -- a count taken off the limited query always equals the number
  -- of rows returned and silently reports every truncated list as complete.
  exit_modules_all as (
    select
      m.title as module_title,
      s.title as subject_title,
      count(*)::int as devices
    from last_module lm
    join modules  m on m.id = lm.module_id
    join subjects s on s.id = lm.subject_id
    group by m.title, s.title
  ),
  exit_subjects_all as (
    select
      s.title as subject_title,
      count(*)::int as devices
    from last_module lm
    join subjects s on s.id = lm.subject_id
    group by s.title
  )
  select json_build_object(
    'since', p_since,
    'until', p_until,
    'depth', (select row_to_json(d) from depth d),
    'exit_modules', json_build_object(
      'rows', (
        select json_agg(row_to_json(t))
        from (
          select module_title, subject_title, devices
          from exit_modules_all
          order by devices desc, module_title
          limit p_limit
        ) t
      ),
      'total_groups', (select count(*)::int from exit_modules_all)
    ),
    'exit_subjects', json_build_object(
      'rows', (
        select json_agg(row_to_json(t))
        from (
          select subject_title, devices
          from exit_subjects_all
          order by devices desc, subject_title
          limit p_limit
        ) t
      ),
      'total_groups', (select count(*)::int from exit_subjects_all)
    )
  );
$$;

revoke execute on function dash_exit_agg(timestamptz, timestamptz, int)
  from public, anon, authenticated;
grant execute on function dash_exit_agg(timestamptz, timestamptz, int) to service_role;

