import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — BSIT Survival Kit",
  description:
    "How BSIT Survival Kit collects, uses, and protects your personal data, in compliance with the Philippine Data Privacy Act of 2012 (RA 10173).",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-paper px-6 py-12 md:px-16 md:py-20">
      <div className="max-w-prose mx-auto">

        <Link
          href="/"
          className="font-sans text-sm text-ink-muted hover:text-ink transition-colors mb-10 inline-block"
        >
          ← Back to home
        </Link>

        <p className="font-mono text-label-md uppercase tracking-[0.1em] text-ink-muted mb-4">
          Legal
        </p>
        <h1 className="font-serif text-display-lg text-ink mb-3 leading-tight">
          Privacy Policy
        </h1>
        <p className="font-sans text-sm text-ink-faint mb-12">
          Last updated: June 2026 &mdash; Compliant with the Philippine Data Privacy Act of 2012 (RA 10173)
        </p>

        <div className="font-sans text-base text-ink-muted leading-relaxed space-y-10">

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">1. Who We Are</h2>
            <p>
              BSIT Survival Kit is a study guide app for Filipino BSIT (Bachelor of
              Science in Information Technology) students. It is operated by a single
              independent developer.
            </p>
            <p className="mt-3">
              As the personal information controller under RA 10173, the developer also
              serves as the Data Protection Officer (DPO). You can reach the DPO at:{" "}
              <a
                href="mailto:paneslawrence8@gmail.com"
                className="text-ink hover:text-accent transition-colors underline underline-offset-2"
              >
                paneslawrence8@gmail.com
              </a>
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">2. What We Collect</h2>
            <p className="mb-4">We only collect what we actually need. Here is what that looks like:</p>

            <div className="space-y-5">
              <div>
                <p className="font-sans font-medium text-ink mb-1">Name and email address</p>
                <p>
                  Collected when you join our waitlist or sign up for a coming-soon
                  notification. We do not collect this unless you voluntarily submit it.
                </p>
              </div>

              <div>
                <p className="font-sans font-medium text-ink mb-1">Device ID</p>
                <p>
                  A randomly generated identifier (UUID) stored in your browser&apos;s
                  local storage. It is generated by your browser the first time you visit
                  and stays on your device. This is not tied to your identity unless you
                  also sign up with your email.
                </p>
              </div>

              <div>
                <p className="font-sans font-medium text-ink mb-1">Behavioral data</p>
                <p>
                  Pages you visit, modules you open, and sections you read. This is
                  linked to your device ID, not your name or email, unless you have
                  signed up. We use this to remember your reading progress and to
                  understand how students use the app.
                </p>
              </div>

              <div>
                <p className="font-sans font-medium text-ink mb-1">GCash payment data</p>
                <p>
                  If you purchase access to premium content, we collect your GCash
                  reference number and the amount paid. We do not collect your GCash
                  account number or any bank credentials.
                </p>
              </div>

              <div>
                <p className="font-sans font-medium text-ink mb-1">Code you submit in the playground</p>
                <p>
                  When you run code in the IDE playground, your code is sent to Judge0
                  (a third-party code execution service at ce.judge0.com) for processing.
                  We do not store your submitted code on our own servers.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">3. Why We Collect It</h2>
            <div className="space-y-3">
              <p>
                <span className="text-ink font-medium">Waitlist name and email</span> —
                to notify you when content becomes available or when we launch. We will
                not use your email for anything else without your permission.
              </p>
              <p>
                <span className="text-ink font-medium">Device ID and behavioral data</span> —
                to save your reading progress across visits and to understand which
                modules students find most useful, so we can improve the app.
              </p>
              <p>
                <span className="text-ink font-medium">Payment data</span> —
                to verify your payment and activate your access to premium content.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">4. Third Parties We Share Data With</h2>
            <p className="mb-4">
              We use a small number of trusted services to run the app. Here is what each
              one sees:
            </p>
            <div className="space-y-4">
              <div>
                <p className="font-medium text-ink mb-1">
                  Supabase{" "}
                  <span className="font-normal text-ink-faint text-sm">(Database — Singapore region)</span>
                </p>
                <p>
                  Stores your name, email, device ID, and behavioral events. Data is
                  hosted in Singapore. Supabase complies with relevant data protection
                  standards.
                </p>
              </div>
              <div>
                <p className="font-medium text-ink mb-1">
                  Vercel{" "}
                  <span className="font-normal text-ink-faint text-sm">(Web hosting — global edge network)</span>
                </p>
                <p>
                  Serves the app globally. Vercel may process request metadata (IP
                  addresses, headers) as part of normal web hosting operations, subject
                  to their own privacy policy.
                </p>
              </div>
              <div>
                <p className="font-medium text-ink mb-1">
                  Judge0{" "}
                  <span className="font-normal text-ink-faint text-sm">(Code execution — ce.judge0.com)</span>
                </p>
                <p>
                  When you run code in the playground, your code is sent to the Judge0
                  community instance for execution. Do not submit sensitive or personal
                  data as code. Judge0 is an independent service with its own terms and
                  privacy policy.
                </p>
              </div>
            </div>
            <p className="mt-4">
              We do not sell your data to anyone.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">5. Your Rights Under RA 10173</h2>
            <p className="mb-4">
              As a data subject under the Philippine Data Privacy Act, you have the
              following rights:
            </p>
            <ul className="space-y-3 list-none">
              {[
                ["Right to be informed", "You have the right to know what data we collect and why. This policy is how we fulfill that."],
                ["Right to access", "You can request a copy of the personal data we hold about you."],
                ["Right to rectify", "You can ask us to correct inaccurate or incomplete data."],
                ["Right to erasure", "You can ask us to delete your personal data. We will comply unless we are legally required to retain it."],
                ["Right to object", "You can object to how we process your data, including for analytics purposes."],
                ["Right to data portability", "You can request your data in a structured, commonly used format."],
                ["Right to file a complaint", "If you believe your rights have been violated, you can file a complaint with the National Privacy Commission at privacy.gov.ph."],
              ].map(([title, description]) => (
                <li key={title} className="flex gap-3">
                  <span className="font-mono text-accent mt-0.5 shrink-0">—</span>
                  <p>
                    <span className="text-ink font-medium">{title}</span>{" "}
                    — {description}
                  </p>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">6. How to Exercise Your Rights</h2>
            <p>
              Email us at{" "}
              <a
                href="mailto:paneslawrence8@gmail.com?subject=Data%20Privacy%20Request"
                className="text-ink hover:text-accent transition-colors underline underline-offset-2"
              >
                paneslawrence8@gmail.com
              </a>{" "}
              with the subject line <span className="font-mono text-sm bg-ink/5 px-1.5 py-0.5 rounded">Data Privacy Request</span>.
              Please describe what you are requesting (access, correction, deletion, etc.)
              and we will respond within a reasonable time, and no later than the period
              required under NPC Circular 16-01.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">7. Data Retention</h2>
            <div className="space-y-3">
              <p>
                <span className="text-ink font-medium">Waitlist name and email</span> —
                kept until the product launches or until you request deletion, whichever
                comes first.
              </p>
              <p>
                <span className="text-ink font-medium">Behavioral and analytics data</span> —
                retained for up to 12 months, then deleted or anonymized.
              </p>
              <p>
                <span className="text-ink font-medium">Payment records</span> —
                kept for as long as necessary to resolve disputes and comply with any
                applicable accounting or legal obligations.
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">8. Security</h2>
            <p>
              Your data is stored in Supabase with encrypted connections (TLS in
              transit, AES-256 at rest). Admin access to the dashboard is protected by
              password authentication. We apply reasonable technical measures to protect
              your data, but no system is completely immune to breaches. If a breach
              occurs that affects your rights, we will notify you and the National
              Privacy Commission as required by law.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-ink mb-3">9. Contact</h2>
            <p>
              For any privacy-related questions, requests, or concerns, reach out to the
              Data Protection Officer:
            </p>
            <p className="mt-3">
              <a
                href="mailto:paneslawrence8@gmail.com"
                className="text-ink hover:text-accent transition-colors underline underline-offset-2"
              >
                paneslawrence8@gmail.com
              </a>
            </p>
          </section>

          <div className="border-t border-ink-faint/20 pt-8">
            <p className="font-mono text-label-sm text-ink-faint">
              This policy was written in plain English on purpose. If something is unclear,
              email us and we will explain it.
            </p>
          </div>

        </div>
      </div>
    </main>
  );
}
